// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// distances
SEXP distances(NumericVector x1, NumericVector y1, NumericVector x2, NumericVector y2);
RcppExport SEXP _OFE_distances(SEXP x1SEXP, SEXP y1SEXP, SEXP x2SEXP, SEXP y2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2(y2SEXP);
    rcpp_result_gen = Rcpp::wrap(distances(x1, y1, x2, y2));
    return rcpp_result_gen;
END_RCPP
}
// correctOverlaps
SEXP correctOverlaps(NumericVector x, NumericVector y, NumericVector yield, double width);
RcppExport SEXP _OFE_correctOverlaps(SEXP xSEXP, SEXP ySEXP, SEXP yieldSEXP, SEXP widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yield(yieldSEXP);
    Rcpp::traits::input_parameter< double >::type width(widthSEXP);
    rcpp_result_gen = Rcpp::wrap(correctOverlaps(x, y, yield, width));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OFE_distances", (DL_FUNC) &_OFE_distances, 4},
    {"_OFE_correctOverlaps", (DL_FUNC) &_OFE_correctOverlaps, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_OFE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
