# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distances <- function(x1, y1, x2, y2) {
    .Call('_OFE_distances', PACKAGE = 'OFE', x1, y1, x2, y2)
}

correctOverlaps <- function(x, y, yield, width) {
    .Call('_OFE_correctOverlaps', PACKAGE = 'OFE', x, y, yield, width)
}

